import Head from 'next/head';
import Hero from '../components/home/Hero';
import GetInvolveCard from '../components/home/GetInvolveCard';
import Widget from '../components/home/Widget';
import Footer from '../components/common/Footer';
import SocMed from '../components/home/SocMed';

export default function Home() {
  return (
    <>
      <Head>
        <title>Winner Church | Global Harvest Ministries Inc.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mb-8">
        <Hero />
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 max-w-[1400px] w-full mx-auto">
          <div className="lg:col-span-6 col-span-1">
            <GetInvolveCard />
          </div>
          <div className="lg:col-span-6 col-span-1">
            <Widget />
          </div>
        </div>
      </main>
      <SocMed />
      <Footer />
    </>
  );
}
